// Build script: base64-encode the blank packaging mockups into api/_mockups.js
// so the serverless wrap endpoint has ZERO filesystem dependency on Vercel.
// (The old api/mockup.js read from disk and fell back to a hardcoded C:\Users path
//  that only exists on the author's laptop — broken in the cloud.)
//
// Run from prototype-app/:  node scripts/build-mockups.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const MOCKUP_DIR = path.join(ROOT, 'public', 'mockup');
const OUT = path.join(ROOT, 'api', '_mockups.js');

// Only the mockups actually offered in MockupStudio. The three logo'd / duplicate
// files in public/mockup are intentionally excluded.
const FILES = {
  'pouch-front-back': 'pouch-front-back-blank.jpg',
  'pouch-isometric': 'pouch-isometric-blank.jpg',
  'pouch-lifestyle': 'pouch-lifestyle-blank.jpg',
  'jar-front': 'jar-front-blank.jpg',
  'jar-lifestyle': 'jar-lifestyle-blank.jpg',
  'box-isometric': 'box-isometric-blank.jpg',
  'box-lifestyle': 'box-lifestyle-blank.jpg',
  'tube-front': 'tube-front-blank.jpg',
  'tub-front': 'tub-front-blank.jpg',
};

let totalKB = 0;
const entries = Object.entries(FILES).map(([id, file]) => {
  const buf = fs.readFileSync(path.join(MOCKUP_DIR, file));
  totalKB += buf.length / 1024;
  return `  '${id}': { mimeType: 'image/jpeg', data: '${buf.toString('base64')}' },`;
});

const banner = `// AUTO-GENERATED by scripts/build-mockups.mjs — do not edit by hand.
// Blank packaging mockups, base64-encoded so api/mockup.js needs no filesystem on Vercel.
// Regenerate after changing public/mockup/ :  node scripts/build-mockups.mjs
`;

fs.writeFileSync(OUT, `${banner}export const MOCKUPS = {\n${entries.join('\n')}\n};\n`);
console.log(`Wrote ${OUT}`);
console.log(`${entries.length} mockups, ${Math.round(totalKB)}KB raw (~${Math.round(totalKB * 1.34)}KB base64).`);
